insert into operadora (nome) values ('ALLIAZ SEGUROS');
insert into operadora (nome) values ('AMEPLAN');
insert into operadora (nome) values ('AMIL');
insert into operadora (nome) values ('BIO SAÚDE');
insert into operadora (nome) values ('BIO VIDA');
insert into operadora (nome) values ('BRADESCO SAÚDE');
insert into operadora (nome) values ('CAIXA SEGURO SAÚDE');
insert into operadora (nome) values ('CAIXA/ADMIX');
insert into operadora (nome) values ('CORPORE GNDI');
insert into operadora (nome) values ('GARANTIA SAÚDE');
insert into operadora (nome) values ('GARANTIA SAÚDE ADVENTISTA');
insert into operadora (nome) values ('GNDI - NOTREDAME INTERMEDICA');
insert into operadora (nome) values ('GREEN LINE');
insert into operadora (nome) values ('GREEN LINE');
insert into operadora (nome) values ('MARITIMA');
insert into operadora (nome) values ('MEDICAL HEALTH');
insert into operadora (nome) values ('NEXT SEISA');
insert into operadora (nome) values ('NEXT SEISA');
insert into operadora (nome) values ('OESTE');
insert into operadora (nome) values ('PLENA');
insert into operadora (nome) values ('PORTO SEGURO');
insert into operadora (nome) values ('SANTA HELENA');
insert into operadora (nome) values ('SÃO CRISTOVÃO');
insert into operadora (nome) values ('SÃO ICHEL SAÚDE');
insert into operadora (nome) values ('SUL AMÉRICA');
insert into operadora (nome) values ('TRASMONTANO');
insert into operadora (nome) values ('AMIL DENTAL');
insert into operadora (nome) values ('BRADESCO DENTAL');
insert into operadora (nome) values ('DENTALPAR');
insert into operadora (nome) values ('DENTALPLUS');
insert into operadora (nome) values ('ODONTOPREV');
insert into operadora (nome) values ('PREVIDENT');
insert into operadora (nome) values ('SUL AMÉRICA');
insert into operadora (nome) values ('UNIODONTO');
insert into operadora (nome) values ('CORPORE AMEPLAN');
insert into operadora (nome) values ('CORPORE AMEPLAN MIDDLE');
insert into operadora (nome) values ('CORPORE DEMAIS PRODUTOS');
insert into operadora (nome) values ('QUALICORP');
insert into operadora (nome) values ('AMEPLAN');
insert into operadora (nome) values ('AMIL DENTAL');
insert into operadora (nome) values ('BIOVIDA / BIOVIDA SENIOR');
insert into operadora (nome) values ('GARANTIA SAÚDE'); 
insert into operadora (nome) values ('GARANTIA SAÚDE ADVENTISTA');
insert into operadora (nome) values ('GREENLINE SENIOR');
insert into operadora (nome) values ('MEDIAL HEALTH');
insert into operadora (nome) values ('NEXT SAÚDE');
insert into operadora (nome) values ('OESTE SAÚDE');
insert into operadora (nome) values ('PLENA');
insert into operadora (nome) values ('PREVIDENT');
insert into operadora (nome) values ('SÃO CRISTÓVÃO (ATÉ 58 ANOS) C/ COPARTICIPAÇÃO');
insert into operadora (nome) values ('SÃO MICHEL SAÚDE');
INSERT INTO usuario (senha, user_name) values ('$2a$10$ROak1.PTNN2Nl/qL27d/uumTKtRa844KO9TDxqDsGSt31ZUKo0fbe', 'wsm1986@gmail.com');
INSERT INTO role (nome) values ('ROLE_ADMIN');
INSERT INTO usuario_roles (user_id, roles_id) values (1, 1);
INSERT INTO employee(name, last_name, email, phone, active) values ('Gustavo VIADO','Ponce','test@test.com','1234567890',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Bob','Marley','one@love.com','6483748590',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('David','Gilmour','high@hopes.com','7648909831',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('John','Lennon','standby@me.com','7689485620',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Ozzy','Osbourne','children@grave.com','6483748590',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('Jimmy','Page','stairway@heaven.com','7648909831',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Jimi','Hendrix','purple@haze.com','8754091236',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('Sex','Pistols','save@queen.com','6729098761',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Jim','Morrison','riders@storm.com','8754091236',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('Richard','Blackmore','highway@star.com','8754091236',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Jay','Kay','cosmic@girl.com','0926389871',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('David','Bowie','heroes@oneday.com','4338490981',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Bob','Dylan','knocking@doors.com','4338490981',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('Manu','Chao','mala@vida.com','8923098753',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('The','Specials','ghost@thown.com','7590498573',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Jymmy','Cliff','see@clearly.com','4338490981',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('The','Temptations','my@girl.com','7639864096',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Simon','Garfunkel','mr@robinson.com','8750987531',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('catch','22','takes@sometime.com','7098653427',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Janis','Joplin','cry@baby.com','6739087641',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('Lou','Red','wild@side.com','6789045678',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Iggy','Pop','the@passenger.com','6934980751',true);
INSERT INTO employee(name, last_name, email, phone, active) values ('Dead','Kennedys','holiday@cambodia.com','2389096457',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('The','Cure','dont@cry.com','8749340987',false);
INSERT INTO employee(name, last_name, email, phone, active) values ('WELL','Cure','dont@cry.com','8749340987',false);


