insert into operadora (nome) values ('ALLIAZ SEGUROS');
insert into operadora (nome) values ('AMEPLAN');
insert into operadora (nome) values ('AMIL');
insert into operadora (nome) values ('BIO SAÚDE');
insert into operadora (nome) values ('BIO VIDA');
insert into operadora (nome) values ('BRADESCO SAÚDE');
insert into operadora (nome) values ('CAIXA SEGURO SAÚDE');
insert into operadora (nome) values ('CAIXA/ADMIX');
insert into operadora (nome) values ('CORPORE GNDI');
insert into operadora (nome) values ('GARANTIA SAÚDE');
insert into operadora (nome) values ('GARANTIA SAÚDE ADVENTISTA');
insert into operadora (nome) values ('GNDI - NOTREDAME INTERMEDICA');
insert into operadora (nome) values ('GREEN LINE');
insert into operadora (nome) values ('GREEN LINE');
insert into operadora (nome) values ('MARITIMA');
insert into operadora (nome) values ('MEDICAL HEALTH');
insert into operadora (nome) values ('NEXT SEISA');
insert into operadora (nome) values ('NEXT SEISA');
insert into operadora (nome) values ('OESTE');
insert into operadora (nome) values ('PLENA');
insert into operadora (nome) values ('PORTO SEGURO');
insert into operadora (nome) values ('SANTA HELENA');
insert into operadora (nome) values ('SÃO CRISTOVÃO');
insert into operadora (nome) values ('SÃO ICHEL SAÚDE');
insert into operadora (nome) values ('SUL AMÉRICA');
insert into operadora (nome) values ('TRASMONTANO');
insert into operadora (nome) values ('AMIL DENTAL');
insert into operadora (nome) values ('BRADESCO DENTAL');
insert into operadora (nome) values ('DENTALPAR');
insert into operadora (nome) values ('DENTALPLUS');
insert into operadora (nome) values ('ODONTOPREV');
insert into operadora (nome) values ('PREVIDENT');
insert into operadora (nome) values ('SUL AMÉRICA');
insert into operadora (nome) values ('UNIODONTO');
insert into operadora (nome) values ('CORPORE AMEPLAN');
insert into operadora (nome) values ('CORPORE AMEPLAN MIDDLE');
insert into operadora (nome) values ('CORPORE DEMAIS PRODUTOS');
insert into operadora (nome) values ('QUALICORP');
insert into operadora (nome) values ('AMEPLAN');
insert into operadora (nome) values ('AMIL DENTAL');
insert into operadora (nome) values ('BIOVIDA / BIOVIDA SENIOR');
insert into operadora (nome) values ('GARANTIA SAÚDE'); 
insert into operadora (nome) values ('GARANTIA SAÚDE ADVENTISTA');
insert into operadora (nome) values ('GREENLINE SENIOR');
insert into operadora (nome) values ('MEDIAL HEALTH');
insert into operadora (nome) values ('NEXT SAÚDE');
insert into operadora (nome) values ('OESTE SAÚDE');
insert into operadora (nome) values ('PLENA');
insert into operadora (nome) values ('PREVIDENT');
insert into operadora (nome) values ('SÃO CRISTÓVÃO (ATÉ 58 ANOS) C/ COPARTICIPAÇÃO');
insert into operadora (nome) values ('SÃO MICHEL SAÚDE');
